[RTCPeerConnection-track-stats.https.html]
  [addTrack() without setLocalDescription() yields track stats]
    expected: FAIL

  [addTrack() without setLocalDescription() yields media stream stats]
    expected: FAIL

  [addTrack() with setLocalDescription() yields track stats]
    expected: FAIL

  [addTrack() with setLocalDescription() yields media stream stats]
    expected: FAIL

  [addTrack(): Media stream stats references track stats]
    expected: FAIL

  [Legacy addStream(): Media stream stats references track stats]
    expected: FAIL

  [O/A exchange yields outbound RTP stream stats for sending track]
    expected: FAIL

  [O/A exchange yields inbound RTP stream stats for receiving track]
    expected: FAIL

  [replaceTrack() before offer: new track attachment stats present]
    expected: FAIL

  [replaceTrack() after offer, before answer: new track attachment stats present]
    expected: FAIL

  [replaceTrack() after answer: new track attachment stats present]
    expected: FAIL

  [replaceTrack(): original track attachment stats present after replacing]
    expected: FAIL

  [RTCRtpSender.getStats() contains only outbound-rtp and related stats]
    expected: FAIL

  [RTCRtpReceiver.getStats() contains only inbound-rtp and related stats]
    expected: FAIL

  [RTCPeerConnection.getStats(track) throws InvalidAccessError when there are zero senders or receivers for the track]
    expected: FAIL

  [RTCPeerConnection.getStats(track) throws InvalidAccessError when there are multiple senders for the track]
    expected: FAIL

  [RTCPeerConnection.getStats(receivingTrack) is the same as RTCRtpReceiver.getStats()]
    disabled:
      if debug and not webrender and not e10s and (os == "linux") and (version == "Ubuntu 16.04") and (processor == "x86") and (bits == 32): wpt-sync Bug 1453975

