[collections.py]
  [test_arguments]
    bug: 1453057
    expected: FAIL

